# Site settings

# Title of the site
title: "My awesome site"
base_url: "http://charmander.charmander"

# Basic meta description for pages that don't have one specified
description: "A basic, incredible site."

# Replace with your Google Analytics ID, eg: UA-12345678-9
google_analytics_id: ''

# Show a warning to users of IE 8 and below
show_ie_warning: True

## Social Media Settings
twitter_username: ''
twitter_image: ''

# Build settings
markdown: kramdown
permalink: pretty

source: app/
destination: _deploy/